# Generated by Django 3.1.7 on 2021-03-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='complaint',
            new_name='feedback',
        ),
    ]
