# Generated by Django 3.1.7 on 2021-03-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210302_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('store', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField()),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
    ]
