# Generated by Django 3.1.7 on 2021-03-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210307_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
