# Generated by Django 3.1.7 on 2021-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210325_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcomment',
            name='id',
        ),
        migrations.AddField(
            model_name='itemcomment',
            name='sno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
