# Generated by Django 3.1.7 on 2021-04-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210327_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
